# Generated by Django 5.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multilinks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkitem",
            name="comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
