# Generated by Django 5.0.6 on 2026-09-14 11:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilinks', '0002_linkitem_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(editable=False, max_length=8, unique=True)),
                ('url', models.URLField(max_length=2000)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='linkitem',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
